version: "3.1"
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - /c/Users/Mohammed_Alam/learning/data/nexus/data/:/nexus-data/